#!/usr/bin/env node

/**
 * ClickUp API starter for MindTheMove operations.
 *
 * Usage examples:
 * node --env-file=.env.local scripts/clickup-starter.mjs health
 * node --env-file=.env.local scripts/clickup-starter.mjs discover
 * node --env-file=.env.local scripts/clickup-starter.mjs create-task "Call new conveyancing leads" "Follow up on weekend submissions"
 * node --env-file=.env.local scripts/clickup-starter.mjs morning-planning
 */

const API_BASE = "https://api.clickup.com/api/v2";

const token = process.env.CLICKUP_TOKEN;
const listId = process.env.CLICKUP_LIST_ID;
const defaultAssignee = process.env.CLICKUP_DEFAULT_ASSIGNEE_ID;

async function clickup(path, options = {}) {
  if (!token) {
    throw new Error("Missing CLICKUP_TOKEN. Add it to .env.local and run with --env-file=.env.local");
  }

  const response = await fetch(`${API_BASE}${path}`, {
    ...options,
    headers: {
      Authorization: token,
      "Content-Type": "application/json",
      ...(options.headers || {}),
    },
  });

  const isJson = response.headers.get("content-type")?.includes("application/json");
  const body = isJson ? await response.json() : await response.text();

  if (!response.ok) {
    throw new Error(`ClickUp ${response.status}: ${JSON.stringify(body)}`);
  }

  return body;
}

function dueAt(hour = 9, minute = 0) {
  const d = new Date();
  d.setDate(d.getDate() + 1);
  d.setHours(hour, minute, 0, 0);
  return d.getTime();
}

async function health() {
  const teams = await clickup("/team");
  console.log("✅ ClickUp API token works");
  console.log(`Teams found: ${teams.teams?.length || 0}`);
  for (const t of teams.teams || []) {
    console.log(`- ${t.name} (${t.id})`);
  }
}

async function discover() {
  const teams = await clickup("/team");
  for (const team of teams.teams || []) {
    console.log(`\nTEAM: ${team.name} (${team.id})`);
    const spaces = await clickup(`/team/${team.id}/space`);
    for (const space of spaces.spaces || []) {
      console.log(`  SPACE: ${space.name} (${space.id})`);
      const folders = await clickup(`/space/${space.id}/folder`);
      for (const folder of folders.folders || []) {
        console.log(`    FOLDER: ${folder.name} (${folder.id})`);
        for (const l of folder.lists || []) {
          console.log(`      LIST: ${l.name} (${l.id})`);
        }
      }
      const folderless = await clickup(`/space/${space.id}/list`);
      for (const l of folderless.lists || []) {
        console.log(`    LIST (no folder): ${l.name} (${l.id})`);
      }
    }
  }
}

async function createTask(name, description = "") {
  if (!listId) {
    throw new Error("Missing CLICKUP_LIST_ID in env.");
  }

  const payload = {
    name,
    description,
    due_date: dueAt(9, 0),
    priority: 3,
    assignees: defaultAssignee ? [Number(defaultAssignee)] : undefined,
    tags: ["mindthemove", "ops"],
  };

  const task = await clickup(`/list/${listId}/task`, {
    method: "POST",
    body: JSON.stringify(payload),
  });

  console.log("✅ Created task:");
  console.log(`- ${task.name} (${task.id})`);
  console.log(`- ${task.url}`);
}

async function morningPlanning() {
  if (!listId) {
    throw new Error("Missing CLICKUP_LIST_ID in env.");
  }

  const checklist = [
    "Review new leads from last 24h",
    "Contact pending business applicants",
    "Check cheapest CZ weekend flight opportunities",
  ];

  const task = await clickup(`/list/${listId}/task`, {
    method: "POST",
    body: JSON.stringify({
      name: "MindTheMove daily planning",
      description: "Autogenerated daily ops task.",
      due_date: Date.now() + 2 * 60 * 60 * 1000,
      priority: 2,
      assignees: defaultAssignee ? [Number(defaultAssignee)] : undefined,
      tags: ["mindthemove", "daily"],
    }),
  });

  for (const item of checklist) {
    await clickup(`/task/${task.id}/checklist`, {
      method: "POST",
      body: JSON.stringify({ name: item }),
    });
  }

  console.log("✅ Daily planning task created:");
  console.log(task.url);
}

async function main() {
  const cmd = process.argv[2];

  if (!cmd) {
    console.log("Usage: node --env-file=.env.local scripts/clickup-starter.mjs <health|discover|create-task|morning-planning>");
    process.exit(1);
  }

  switch (cmd) {
    case "health":
      await health();
      break;
    case "discover":
      await discover();
      break;
    case "create-task":
      await createTask(process.argv[3] || "MindTheMove task", process.argv[4] || "");
      break;
    case "morning-planning":
      await morningPlanning();
      break;
    default:
      throw new Error(`Unknown command: ${cmd}`);
  }
}

main().catch((err) => {
  console.error("❌", err.message);
  process.exit(1);
});
